/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul_7_GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class praktikum_3 extends javax.swing.JFrame {

    /**
     * Creates new form praktikum_3
     */
    public praktikum_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tempatLahir = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        asalSekolah = new javax.swing.JTextField();
        hp = new javax.swing.JTextField();
        nun = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tanggalLahir = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        minNUN = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kgsp = new javax.swing.JRadioButton();
        dpib = new javax.swing.JRadioButton();
        tptu = new javax.swing.JRadioButton();
        rpl = new javax.swing.JRadioButton();
        tb = new javax.swing.JRadioButton();
        akl = new javax.swing.JRadioButton();
        tp = new javax.swing.JRadioButton();
        nunkurang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Form Pendaftaran Siswa Baru SMK Negeri 2 Trenggalek");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Copyright © 2023 Rafly Nur Ihvandi");

        jLabel3.setText("Nama");

        jLabel4.setText("Tempat / Tanggal Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Umur");

        jLabel7.setText("Asal Sekolah");

        jLabel8.setText("No HP");

        jLabel9.setText("NUN");

        jLabel10.setText("Alamat");

        jButton1.setText("KIRIM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jeniskelamin.add(laki);
        laki.setText("Laki - Laki");

        jeniskelamin.add(perempuan);
        perempuan.setText("Perempuan");

        jLabel11.setText("Jurusan yang Dipilih");

        jurusan.add(kgsp);
        kgsp.setText("KGSP");

        jurusan.add(dpib);
        dpib.setText("BPIB");

        jurusan.add(tptu);
        tptu.setText("TPTU");

        jurusan.add(rpl);
        rpl.setText("RPL");

        jurusan.add(tb);
        tb.setText("TB");

        jurusan.add(akl);
        akl.setText("AKL");

        jurusan.add(tp);
        tp.setText("TP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(minNUN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kgsp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dpib)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tptu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rpl)
                                        .addGap(18, 18, 18)
                                        .addComponent(tb)
                                        .addGap(18, 18, 18)
                                        .addComponent(akl)
                                        .addGap(18, 18, 18)
                                        .addComponent(tp))
                                    .addComponent(tanggalLahir)))
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(laki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perempuan))
                            .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nun, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nunkurang)
                        .addGap(320, 320, 320))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laki)
                            .addComponent(perempuan)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kgsp)
                    .addComponent(dpib)
                    .addComponent(tptu)
                    .addComponent(rpl)
                    .addComponent(tb)
                    .addComponent(akl)
                    .addComponent(tp)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(nunkurang)
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(minNUN)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nm, tempatL, tanggalL, jenisKel, umr, asalS, noHp, jurusan, nilN, alt, data, pesan;
        double nilNun, nilJurusan;
        nm = nama.getText();
        tempatL = tempatLahir.getText();
        tanggalL = tanggalLahir.getText();
        umr = umur.getText();
        asalS = asalSekolah.getText();
        noHp = hp.getText();
        alt = alamat.getText();
        nilNun = Double.parseDouble(nun.getText());
        
        if(laki.isSelected()){
            jenisKel = "Laki - Laki";
        } else {
            jenisKel = "Perempuan";
        }
        
        if(kgsp.isSelected() && nilNun>=150){
            jurusan = "KGSP";
            nilN = String.valueOf(nilNun);
            pesan = "Selamat Kamu Telah Diterima di SMK Negeri 2 Trenggalek\n";
        } else if(dpib.isSelected() && nilNun>=220){
            jurusan = "DPIB";
            nilN = String.valueOf(nilNun);
            pesan = "Selamat Kamu Telah Diterima di SMK Negeri 2 Trenggalek\n";
        } else if(tptu.isSelected() && nilNun>=170){
            jurusan = "TPTU";
            nilN = String.valueOf(nilNun);
            pesan = "Selamat Kamu Telah Diterima di SMK Negeri 2 Trenggalek\n";
        } else if(rpl.isSelected() && nilNun>=240){
            jurusan = "RPL";
            nilN = String.valueOf(nilNun);
            pesan = "Selamat Kamu Telah Diterima di SMK Negeri 2 Trenggalek\n";
        } else if(tb.isSelected() && nilNun>=120){
            jurusan = "TB";
            nilN = String.valueOf(nilNun);
            pesan = "Selamat Kamu Telah Diterima di SMK Negeri 2 Trenggalek\n";
        } else if(akl.isSelected() && nilNun>=200){
            jurusan = "AKL";
            nilN = String.valueOf(nilNun);
            pesan = "Selamat Kamu Telah Diterima di SMK Negeri 2 Trenggalek\n";
        } else if(kgsp.isSelected() && nilNun<150){
            jurusan = "KGSP";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        } else if(dpib.isSelected() && nilNun<220){
            jurusan = "DPIB";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        } else if(tptu.isSelected() && nilNun<170){
            jurusan = "TPTU";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        } else if(rpl.isSelected() && nilNun<240){
            jurusan = "RPL";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        } else if(tb.isSelected() && nilNun<120){
            jurusan = "TB";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        } else if(akl.isSelected() && nilNun<200){
            jurusan = "AKL";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        } else {
            jurusan = "";
            nilN = String.valueOf(nilNun);
            pesan = "Maaf NUN Kamu Belum Standart Untuk Masuk di SMK Negeri 2 Trenggalek\n";
        }
        
        data = pesan;
        data += "Berikut Data Diri Kamu\n";
        data += "Nama : "+nm+"\n";
        data += "Tempat / Tanggal Lahir : "+tempatL+" / "+tanggalL+"\n";
        data += "Jenis Kelamin : "+jenisKel+"\n";
        data += "Umur : "+umr+"\n";
        data += "Asal Sekolah : "+asalS+"\n";
        data += "No HP : "+noHp+"\n";
        data += "Jurusan yang Dipilih : "+jurusan+"\n";
        data += "NUN : "+nilN+"\n";
        data += "Alamat : "+alt+"\n";
        JOptionPane.showMessageDialog(null, data);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(praktikum_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(praktikum_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(praktikum_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(praktikum_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new praktikum_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton akl;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField asalSekolah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dpib;
    private javax.swing.JTextField hp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.ButtonGroup jurusan;
    private javax.swing.JRadioButton kgsp;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel minNUN;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nun;
    private javax.swing.JLabel nunkurang;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JRadioButton rpl;
    private javax.swing.JTextField tanggalLahir;
    private javax.swing.JRadioButton tb;
    private javax.swing.JTextField tempatLahir;
    private javax.swing.JRadioButton tp;
    private javax.swing.JRadioButton tptu;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
