/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lsp_xii_2023;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Stack;
import static modul_10_ujikom.mykalkulator.operator;

/**
 *
 * @author user
 */
public class kalkulator extends javax.swing.JFrame {
    public static final String operator = "-+/*^%";
    String infix = "";
    String angka = "";
    boolean isValid = false;
    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }
    
    public static String infixToPostfix(String infix) {

        StringBuilder sb = new StringBuilder();
        Stack<Integer> s = new Stack<>();

        for (String token : infix.split("\\s")) {
            if (token.isEmpty()) {
                continue;
            }

            char c = token.charAt(0);
            int indexOperator = operator.indexOf(c);

            if (indexOperator != -1) {
                if (s.isEmpty()) {
                    s.push(indexOperator);
                } else {
                    while (!s.isEmpty()) {
                        int prec2 = s.peek() / 2;
                        int prec1 = indexOperator / 2;
                        if (prec2 > prec1 || (prec2 == prec1 && c != '^')) {
                            sb.append(operator.charAt(s.pop())).append(' ');
                        } else {
                            break;
                        }
                    }
                    s.push(indexOperator);
                }

            } else {
                sb.append(token).append(' ');
            }
        }

        while (!s.isEmpty()) {
            sb.append(operator.charAt(s.pop())).append(' ');
        }

        return sb.toString();
    }
    public static double evaluatePostfix(String postfix) {
        Stack<Double> s = new Stack<>();
        for (String token : postfix.split("\\s")) {
            if (token.isEmpty()) {
                continue;
            }

            if (operator.indexOf(token) == -1) {
                s.push(Double.valueOf(token));
            } else {
                double val1 = s.pop();
                double val2 = s.pop();

                switch (token) {
                    case "+":
                        s.push(val2 + val1);
                        break;
                    case "-":
                        s.push(val2 - val1);
                        break;
                    case "*":
                        s.push(val2 * val1);
                        break;
                    case "/":
                        s.push(val2 / val1);
                        break;
                    case "^":
                        s.push(Math.pow(val2, val1));
                        break;
                    default:
                        throw new AssertionError();
                }
            }
        }
        return s.pop();
    }
    
    public void setOutput(String num) {
        inputField.setText(num);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        pangkatdua = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        duaPx = new javax.swing.JButton();
        Ax = new javax.swing.JButton();
        xPdua = new javax.swing.JButton();
        xPtiga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inputField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        inputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputField.setText("0");
        inputField.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputField)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        clear.setBackground(new java.awt.Color(102, 255, 0));
        clear.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 204));
        clear.setText("CLEAR");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        persen.setBackground(new java.awt.Color(102, 255, 0));
        persen.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        persen.setForeground(new java.awt.Color(255, 255, 204));
        persen.setText("%");
        persen.setBorder(null);
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });

        tambah.setBackground(new java.awt.Color(102, 255, 0));
        tambah.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 204));
        tambah.setText("+");
        tambah.setBorder(null);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        tujuh.setBackground(new java.awt.Color(102, 255, 0));
        tujuh.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tujuh.setText("7");
        tujuh.setBorder(null);
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });

        delapan.setBackground(new java.awt.Color(102, 255, 0));
        delapan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        delapan.setText("8");
        delapan.setBorder(null);
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });

        kurang.setBackground(new java.awt.Color(102, 255, 0));
        kurang.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kurang.setForeground(new java.awt.Color(255, 255, 204));
        kurang.setText("-");
        kurang.setBorder(null);
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        sembilan.setBackground(new java.awt.Color(102, 255, 0));
        sembilan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        sembilan.setText("9");
        sembilan.setBorder(null);
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });

        kali.setBackground(new java.awt.Color(102, 255, 0));
        kali.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kali.setForeground(new java.awt.Color(255, 255, 204));
        kali.setText("*");
        kali.setBorder(null);
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });

        enam.setBackground(new java.awt.Color(102, 255, 0));
        enam.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        enam.setText("6");
        enam.setBorder(null);
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });

        lima.setBackground(new java.awt.Color(102, 255, 0));
        lima.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lima.setText("5");
        lima.setBorder(null);
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });

        empat.setBackground(new java.awt.Color(102, 255, 0));
        empat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        empat.setText("4");
        empat.setBorder(null);
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });

        hasil.setBackground(new java.awt.Color(255, 255, 204));
        hasil.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        hasil.setForeground(new java.awt.Color(51, 255, 0));
        hasil.setText("=");
        hasil.setBorder(null);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        bagi.setBackground(new java.awt.Color(102, 255, 0));
        bagi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bagi.setForeground(new java.awt.Color(255, 255, 204));
        bagi.setText("/");
        bagi.setBorder(null);
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });

        tiga.setBackground(new java.awt.Color(102, 255, 0));
        tiga.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tiga.setText("3");
        tiga.setBorder(null);
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });

        koma.setBackground(new java.awt.Color(102, 255, 0));
        koma.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        koma.setText(".");
        koma.setBorder(null);
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });

        dua.setBackground(new java.awt.Color(102, 255, 0));
        dua.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dua.setText("2");
        dua.setBorder(null);
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });

        pangkatdua.setBackground(new java.awt.Color(102, 255, 0));
        pangkatdua.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pangkatdua.setForeground(new java.awt.Color(255, 255, 204));
        pangkatdua.setText("x^2");
        pangkatdua.setBorder(null);
        pangkatdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatduaActionPerformed(evt);
            }
        });

        satu.setBackground(new java.awt.Color(102, 255, 0));
        satu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        satu.setText("1");
        satu.setBorder(null);
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });

        nol.setBackground(new java.awt.Color(102, 255, 0));
        nol.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nol.setText("0");
        nol.setBorder(null);
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Copyright © 2023 Rafly Nur Ihvandi");

        duaPx.setBackground(new java.awt.Color(51, 255, 0));
        duaPx.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        duaPx.setForeground(new java.awt.Color(255, 255, 204));
        duaPx.setText("2^x");
        duaPx.setBorder(null);
        duaPx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaPxActionPerformed(evt);
            }
        });

        Ax.setBackground(new java.awt.Color(102, 255, 0));
        Ax.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Ax.setForeground(new java.awt.Color(255, 255, 204));
        Ax.setText("Ax");
        Ax.setBorder(null);
        Ax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AxActionPerformed(evt);
            }
        });

        xPdua.setBackground(new java.awt.Color(102, 255, 0));
        xPdua.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        xPdua.setForeground(new java.awt.Color(255, 255, 204));
        xPdua.setText("x/2");
        xPdua.setBorder(null);
        xPdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPduaActionPerformed(evt);
            }
        });

        xPtiga.setBackground(new java.awt.Color(102, 255, 0));
        xPtiga.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        xPtiga.setForeground(new java.awt.Color(255, 255, 204));
        xPtiga.setText("x^3");
        xPtiga.setBorder(null);
        xPtiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPtigaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(persen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kali, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pangkatdua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(koma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(xPtiga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xPdua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duaPx, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pangkatdua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(koma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xPtiga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xPdua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duaPx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pangkatduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatduaActionPerformed
        int a = Integer.parseInt(angka); 
        double vl = Math.pow(a, 2);
        int v = (int) vl;
        infix = Integer.toString(v);
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_pangkatduaActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        infix += "1";
        angka += "1";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        infix += "2";
        angka += "2";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        infix += "3";
        angka += "3";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        infix += "4";
        angka += "4";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        infix += "5";
        angka += "5";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        infix += "6";
        angka += "6";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        infix += "7";
        angka += "7";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        infix += "8";
        angka += "8";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        infix += "9";
        angka += "9";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_sembilanActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        infix += "0";
        angka += "0";
        isValid = true;
        setOutput(infix);
    }//GEN-LAST:event_nolActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        infix += " + ";
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        infix += " - ";
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        infix += " * ";
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        infix += " / ";
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_bagiActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        if (isValid) {
            String postfix = infixToPostfix(infix);
            infix = "";
            double result = evaluatePostfix(postfix);
            if (result == (int) result) {
                setOutput(String.valueOf((int) result));

            } else {
                setOutput(String.valueOf(result));

            }
        }
    }//GEN-LAST:event_hasilActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        infix = "";
        angka = "";
        setOutput("0");
        isValid = false;
    }//GEN-LAST:event_clearActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        infix += " . ";
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_komaActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        double a = Double.parseDouble(angka); 
        double v = a / 100;
        infix = Double.toString(v);
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_persenActionPerformed

    private void duaPxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaPxActionPerformed
        int a = Integer.parseInt(angka); 
        double vl = Math.pow(2, a);
        int v = (int) vl;
        infix = Integer.toString(v);
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_duaPxActionPerformed

    private void AxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AxActionPerformed
        double a = Double.parseDouble(angka); 
        double v = Math.sqrt(a);
        DecimalFormat df = new DecimalFormat("#.##");
        String vs = df.format(v);
        infix = vs;
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_AxActionPerformed

    private void xPduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPduaActionPerformed
        double a = Double.parseDouble(angka); 
        double v = a / 2;
        infix = Double.toString(v);
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_xPduaActionPerformed

    private void xPtigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPtigaActionPerformed
        int a = Integer.parseInt(angka); 
        double vl = Math.pow(a, 3);
        int v = (int) vl;
        infix = Integer.toString(v);
        isValid = false;
        setOutput(infix);
    }//GEN-LAST:event_xPtigaActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_1) {
            infix += "1";
            setOutput(infix);
        }
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ax;
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton duaPx;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton hasil;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JButton pangkatdua;
    private javax.swing.JButton persen;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    private javax.swing.JButton xPdua;
    private javax.swing.JButton xPtiga;
    // End of variables declaration//GEN-END:variables
}
